# pubspec.yaml
name: tracerx_qr
description: A Flutter app for drug verification using QR codes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.2  # Updated to a known valid version
  vibration: ^3.1.3
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  provider: ^6.1.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/animations/  # Add a folder for Lottie animations if used, e.g., success.json, error.json